export const categories = ["Meat", "Jam", "Drinks"]

export const mockProducts = [
  // Meat
  {
    id: "p-1",
    name: "Fresh Beef",
    price: 12.99,
    category: "Meat",
    image: "/fresh-beef-meat.jpg",
    description: "Premium quality fresh beef, perfect for grilling or frying.",
    unit: "per kg",
  },
  {
    id: "p-2",
    name: "Chicken Breast",
    price: 8.99,
    category: "Meat",
    image: "/chicken-breast-meat.jpg",
    description: "Tender chicken breast with rich protein content.",
    unit: "per kg",
  },
  {
    id: "p-3",
    name: "Lamb Chops",
    price: 15.99,
    category: "Meat",
    image: "/lamb-chops-meat.jpg",
    description: "Succulent lamb chops for roasting and frying.",
    unit: "per kg",
  },
  {
    id: "p-4",
    name: "Ground Turkey",
    price: 9.99,
    category: "Meat",
    image: "/ground-turkey-meat.jpg",
    description: "Lean and healthy ground turkey for everyday meals.",
    unit: "per kg",
  },
  {
    id: "p-5",
    name: "Made in USA",
    price: 9.99,
    category: "Meat",
    image: "/usa-meat-xn.jpg",
    description: "High-quality USA-produced meat cuts.",
    unit: "per kg",
  },

  // Jam
  {
    id: "p-6",
    name: "Strawberry Jam",
    price: 5.99,
    category: "Jam",
    image: "/strawberry-jam-jar.jpg",
    description: "Homemade strawberry jam with natural sweetness.",
    unit: "per jar",
  },
  {
    id: "p-7",
    name: "Apricot Jam",
    price: 6.49,
    category: "Jam",
    image: "/apricot-jam-jar.jpg",
    description: "Delightful apricot preserve made from fresh fruits.",
    unit: "per jar",
  },
  {
    id: "p-8",
    name: "Blueberry Jam",
    price: 6.99,
    category: "Jam",
    image: "/blueberry-jam-jar.jpg",
    description: "Rich blueberry jam with deep fruity flavor.",
    unit: "per jar",
  },
  {
    id: "p-9",
    name: "Orange Marmalade",
    price: 5.49,
    category: "Jam",
    image: "/orange-marmalade-jar.jpg",
    description: "Tangy orange marmalade made with fresh citrus.",
    unit: "per jar",
  },
  {
    id: "p-10",
    name: "Classic Strawberry Jam",
    price: 5.49,
    category: "Jam",
    image: "/strawberry-jam.jpg",
    description: "Classic tangy strawberry jam, perfect for breakfast.",
    unit: "per jar",
  },

  // Drinks
  {
    id: "p-11",
    name: "Cola",
    price: 4.99,
    category: "Drinks",
    image: "/cola.jpg",
    description: "Coca-Cola classic taste for every occasion.",
    unit: "per liter",
  },
  {
    id: "p-12",
    name: "Fresh Orange Juice",
    price: 4.99,
    category: "Drinks",
    image: "/fresh-orange-juice-bottle.jpg",
    description: "Freshly squeezed orange juice full of vitamins.",
    unit: "per liter",
  },
  {
    id: "p-13",
    name: "Apple Cider",
    price: 5.49,
    category: "Drinks",
    image: "/apple-cider-bottle.png",
    description: "Natural apple cider made from organic apples.",
    unit: "per liter",
  },
  {
    id: "p-14",
    name: "Mineral Water",
    price: 2.99,
    category: "Drinks",
    image: "/mineral-water-bottle.jpg",
    description: "Pure and refreshing mineral water.",
    unit: "per liter",
  },
  {
    id: "p-15",
    name: "Green Tea",
    price: 3.99,
    category: "Drinks",
    image: "/green-tea-bottle.jpg",
    description: "Organic green tea with natural antioxidants.",
    unit: "per bottle",
  },
]

export const mockOrders = [
  {
    id: "ORD-1023",
    customer: "Ali V.",
    address: "Tashkent, Chilonzor",
    phone: "+998 90 123 45 67",
    status: "Pending",
    date: "2025-10-10",
    items: [
      { name: "Fresh Beef", qty: 1, price: 12.99 },
      { name: "Strawberry Jam", qty: 2, price: 5.99 },
    ],
    total: 24.97,
  },
  {
    id: "ORD-1022",
    customer: "Laylo M.",
    address: "Samarqand, Bulung‘ur",
    phone: "+998 91 555 22 11",
    status: "Processing",
    date: "2025-10-09",
    items: [{ name: "Cola", qty: 4, price: 4.99 }],
    total: 19.96,
  },
  {
    id: "ORD-1021",
    customer: "Jasur T.",
    address: "Andijon, Asaka",
    phone: "+998 93 777 88 44",
    status: "Delivered",
    date: "2025-10-07",
    items: [
      { name: "Lamb Chops", qty: 1, price: 15.99 },
      { name: "Apple Cider", qty: 2, price: 5.49 },
    ],
    total: 26.97,
  },
]
